### ISSUE TITLE
 Gradle detected a problem with the following location '..\node_modules\@ihealth\ihealthlibrary-react-native\android\build\generated\res\resValues\debug'

### ISSUE THREAD

**Issue by AmilaJJ** [iHealthDeviceLabs/iHealth-React-Native-SDK#6]
I installed the iHealth library for react native. After installation, when I run my project on Android device, I get the following error

* What went wrong:
Some problems were found with the configuration of task ':ihealthlibrary-react-native:packageDebugResources' (type 'MergeResources').
  - Gradle detected a problem with the following location: 'C:\projects\AwesomeProject\node_modules\@ihealth\ihealthlibrary-react-native\android\build\generated\res\rs\debug'.

    Reason: Task ':ihealthlibrary-react-native:packageDebugResources' uses this output of task ':ihealth_ihealthlibrary-react-native:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':ihealth_ihealthlibrary-react-native:compileDebugRenderscript' as an input of ':ihealthlibrary-react-native:packageDebugResources'.
      2. Declare an explicit dependency on ':ihealth_ihealthlibrary-react-native:compileDebugRenderscript' from ':ihealthlibrary-react-native:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':ihealth_ihealthlibrary-react-native:compileDebugRenderscript' from ':ihealthlibrary-react-native:packageDebugResources' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'C:\projects\AwesomeProject\node_modules\@ihealth\ihealthlibrary-react-native\android\build\generated\res\resValues\debug'.

    Reason: Task ':ihealthlibrary-react-native:packageDebugResources' uses this output of task ':ihealth_ihealthlibrary-react-native:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':ihealth_ihealthlibrary-react-native:generateDebugResValues' as an input of ':ihealthlibrary-react-native:packageDebugResources'.
      2. Declare an explicit dependency on ':ihealth_ihealthlibrary-react-native:generateDebugResValues' from ':ihealthlibrary-react-native:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':ihealth_ihealthlibrary-react-native:generateDebugResValues' from ':ihealthlibrary-react-native:packageDebugResources' using Task#mustRunAfter.

**Comment by AmilaJJ** [comment]
this issue fixing after downgraded gradle version to 7.5

**Comment by Oakyden** [comment]
@AmilaJJ are you using expo or bare bones react native?

I am still getting `:ihealth_ihealthlibrary-react-native:compileDebugJavaWithJavac` despite downgrading Gradle to 7.5.1 (as in their example project here https://github.com/iHealthLab/iHealth-rn-sdk/tree/main/example ) 

I would love to know details of your setup and whether you got this package working
